Reset sb buffer when key presed
ii8/havoc pull request #54
Opened 2024-08-27 22:03 UTC by keshto

Normal behavior on most terminal emulators is that the scrollback buffer jumps to bottom (if scrolled up) when something is typed into the terminal. This should emulate that behavior.

2024-08-28 22:28 UTC, ii8 commented
You can use this action to scroll all the way down:
https://github.com/ii8/havoc/blob/9b17b655b3173d08e446b665c20f2fe0fe6da3a1/havoc.cfg#L40

Ctrl + Shift + End if using the example config.

Personally I don't want it to scroll down when something is typed, sometimes one might want to type something while looking at/referencing what is further up in the scrollback.

2024-08-29 08:11 UTC, ii8 commented
Yes that would be fine

2024-08-29 08:15 UTC, keshto commented
Will update the PR, thank you.

On August 29, 2024 8:12:22 AM UTC, Murray ***@***.***> wrote:
>Yes that would be fine
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ii8/havoc/pull/54#issuecomment-2316981015
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

2024-08-30 10:25 UTC, ii8 requested changes
Apologies for the nitpicks

Also please make this PR just one commit

2024-08-30 10:25 UTC, ii8 commented on main.c
> +	.cfg.reset_scrollback = true,
The default should be off.
The default should always be the more minimal behaviour.

2024-08-30 10:25 UTC, ii8 commented on main.c
> +		bool vte_write_success = tsm_vte_handle_keyboard(term.vte, sym, XKB_KEY_NoSymbol,
This variable isn't needed, just put the call in the `if`

2024-08-30 10:25 UTC, ii8 commented on main.c
>  					term.mods, unicode);
Alignment

2024-08-30 10:25 UTC, ii8 commented on main.c
> +	if (!action){
Missing space, there's a space before `{` everywhere else, I'd like it to be consistent

2024-08-30 10:25 UTC, ii8 commented on main.c
> +			term.need_redraw = tsm_screen_sb_reset(term.screen);
This could unset a previously set `need_redraw`, that's not right.

2024-08-30 10:29 UTC, ii8 commented on main.c
> +		bool vte_write_success = tsm_vte_handle_keyboard(term.vte, sym, XKB_KEY_NoSymbol,
I'm also curious, why only scroll down if it returns true here? Is this the behaviour of other terminals?

2024-08-30 10:36 UTC, keshto commented
If there is not that variable check of returning true then it will scroll down on any key press. Imagine one has a terminal open scrolled up and alt+tabs to another window. The alt press would trigger the scroll to bottom which is undesirable. Scroll to bottom should only happen on input to the terminal that would cause the readline to change.

For config option name, what about scroll-to-input ?

Will address other nitpicks. 

On August 30, 2024 10:30:09 AM UTC, Murray ***@***.***> wrote:
>@ii8 commented on this pull request.
>
>
>
>> @@ -1035,9 +1037,12 @@ static void kbd_key(void *data, struct wl_keyboard *k, uint32_t serial,
> 		b = b->next;
> 	}
> 
>-	if (!action)
>-		tsm_vte_handle_keyboard(term.vte, sym, XKB_KEY_NoSymbol,
>+	if (!action){
>+		bool vte_write_success = tsm_vte_handle_keyboard(term.vte, sym, XKB_KEY_NoSymbol,
>
>I'm also curious, why only scroll down if it returns true here? Is this the behaviour of other terminals?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ii8/havoc/pull/54#discussion_r1738386737
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

2024-08-30 13:17 UTC, ii8 commented
Ah ok, makes sense.

Another part of the config already uses the phrase `scroll to bottom` for the same thing, so lets use that here too and make it `scroll to bottom on input`. A bit long, but I found some other terminals use that too. And we can use spaces instead of - or _ because the format of the config is an ini file.

2024-09-02 15:39 UTC, keshto commented
Latest push should reflect requested changes

2024-09-03 19:49 UTC, ii8 commented
merged, ty
6e31fc3c07568cb2d4826e2280246e2f0db0cc53

2024-09-03 19:49 UTC, closed without merging